---
deployment:
  tasks:
    - export DEPLOYPATH=/home/soyeduc1/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp 404.html $DEPLOYPATH
    - /bin/cp about.html $DEPLOYPATH
    - /bin/cp contact.html $DEPLOYPATH
    - /bin/cp courses.html $DEPLOYPATH
    - /bin/cp team.html $DEPLOYPATH
    - /bin/cp testimonial.html $DEPLOYPATH